language: bash

before_script:
  - make clean
  - make prepare

script:
  - make build

notifications:
  email:
    - matthew@baggett.me

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs
  committer_from_gh: true
